services:
  - type: web
    name: redteam-bot
    env: python
    buildCommand: pip install python-telegram-bot requests
    startCommand: python -m bot
    envVars:
      - key: TOKEN
        value: 8812677665:AAGeT4rHVK-IwA8_y5Ir-HMP27U6OPcEPdg
