services:
  - type: web
    name: suicr-cp-lawful-redteam
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        value: 8703097627:AAF6-XdA4mp-hn3Y-tE2D8uME1eIztwFTNY
